package com.geekbrains;

public enum Commands {


    FILE,
    FILE_MESSAGE,
    FILE_REQUEST,
    FILES_LIST,
    FOLDER_REQUEST,
    REGISTRATION,
    REGISTRATION_ERROR,
    AUTHENTICATION,
    AUTHENTICATION_OK,
    AUTHENTICATION_ERROR,
    CHANGE_PASSWORD,
    CHANGE_PASSWORD_OK,
    CHANGE_PASSWORD_ERROR


}
